name: Renovate
on:
  workflow_dispatch:
#  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
#    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: 'renovate.json'


      - name: Verify Go Mod Tidy
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain)" ]; then
            echo "Go module files are not tidy!"
            exit 1
          fi